server:
  port: 8080
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:/Users/vishrutmajmudar/product
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE