apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
  namespace: demo
data:
  config_url: "http://cloud-config-server-svc"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  namespace: demo
data:
  eureka_service_address: http://eureka-0.eureka:8761/eureka
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
  namespace: demo
data:
  hostname: "mysql"