server:
  port: 9090
spring:
  redis:
    host: redis
    port: 6379
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: http://order-service-svc
          predicates:
            - Path=/order/**
        - id: PAYMENT-SERVICE
          uri: http://payment-service-svc
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
        - id: PRODUCT-SERVICE
          uri: http://product-service-svc
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
management:
  metrics:
    tags:
      application : ${spring.application.name}
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,metrics,prometheus
  health:
    redis:
      enabled: true
    readinessState:
      enabled: true
    livenessState:
      enabled: true

okta:
  oauth2:
    issuer: https://dev-02875322.okta.com/oauth2/default
    client-id: 0oa4603aofl1jn4Vk5d7
    client-secret: 8tT0PeHS7N0-nIJzjr4aoHXDo-4aQcHFvh0p-chy
    audience: api://default
    scopes: openid, email, profile, offline_access

logging:
  level:
    root: ERROR
