server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Admin1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-02875322.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa4603aofl1jn4Vk5d7
            client-secret: 8tT0PeHS7N0-nIJzjr4aoHXDo-4aQcHFvh0p-chy
        provider:
          okta:
            issuer-uri: https://dev-02875322.okta.com/oauth2/default
  application:
    name: ORDER-SERVICE
logging:
  level:
    root: info

microservice:
  product: http://product-service-svc/product
  payment: http://payment-service-svc/payment